services:
  - type: web
    name: vocal-removal-backend
    env: python
    plan: free
    buildCommand: ./render-build.sh
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
